### ISSUE TITLE
Scanning error :(

### ISSUE THREAD

**Issue by mekhalleh** [evilsocket/bleah#14]
Hello, just have installed but not work.
Have you an idea ? Thanks.
-----
Scanning for devices...
Traceback (most recent call last):
  File "/usr/local/bin/blescan", line 11, in <module>
    load_entry_point('bluepy==1.1.2', 'console_scripts', 'blescan')()
  File "/usr/local/lib/python2.7/dist-packages/bluepy/blescan.py", line 122, in main
    devices = scanner.scan(arg.timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 679, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 616, in start
    self._startHelper(iface=self.iface)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 246, in _startHelper
    universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by evilsocket** [comment]
Instal bluepy as explained in the README.
