### ISSUE TITLE
bluepy.btle.BTLEException: Device disconnected

### ISSUE THREAD

**Issue by michelep** [evilsocket/bleah#17]
@ Continuous scanning [-128 dBm of sensitivity] ...

┌ fc:8f:90:af:xx:xx (-88 dBm) ─────────────────────────────────────────────────┐
│ Vendor             │ Samsung Electronics Co.                                 │
│ Allows Connections │ ✓                                                       │
│ Flags              │                                                         │
│ Manufacturer       │ u'750042040101affc8f90af738cfe8f90af7xxxxxxxxxxxxxx' │
└────────────────────┴─────────────────────────────────────────────────────────┘

Traceback (most recent call last):
  File "/usr/local/bin/bleah", line 4, in <module>
    __import__('pkg_resources').run_script('bleah==1.0.0', 'bleah')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 118, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 78, in main
    devices = start_scan(args)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py", line 162, in start_scan
    return scanner.scan(args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 681, in scan
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 630, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 272, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 326, in _waitResp
    raise BTLEException(BTLEException.DISCONNECTED, "Device disconnected")
bluepy.btle.BTLEException: Device disconnected

**Comment by rousez** [comment]
Interesting, I am also getting this error as of 15 minutes ago.  Problem is that I wasn't getting this before like an hour ago.

**Comment by rousez** [comment]
Hmm, okay I rebooted my raspberry pi that I am using to run bleah and ran again when it came up and that  seem to resolve this issue.  Try rebooting the machine you are using.

**Comment by lokeshh** [comment]
I keep getting this error randomly.
