### ISSUE TITLE
build issue - Bash Windows

### ISSUE THREAD

**Issue by ARH-Digital** [evilsocket/bleah#19]
Attempting to install this on Ubuntu - Windows Bash
I get the following error when trying to build 

```
root@DESKTOP-L593AS0:~/bleah# uname -a
Linux DESKTOP-L593AS0 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I have installed the required bluepy and termibaltables
```
root@DESKTOP-L593AS0:~/bleah# python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/bleah
copying bleah/__init__.py -> build/lib.linux-x86_64-2.7/bleah
copying bleah/enumerate.py -> build/lib.linux-x86_64-2.7/bleah
copying bleah/scan.py -> build/lib.linux-x86_64-2.7/bleah
copying bleah/swag.py -> build/lib.linux-x86_64-2.7/bleah
copying bleah/vendors.py -> build/lib.linux-x86_64-2.7/bleah
copying bleah/version.py -> build/lib.linux-x86_64-2.7/bleah
copying bleah/write.py -> build/lib.linux-x86_64-2.7/bleah
running egg_info
creating bleah.egg-info
writing requirements to bleah.egg-info/requires.txt
writing bleah.egg-info/PKG-INFO
writing top-level names to bleah.egg-info/top_level.txt
writing dependency_links to bleah.egg-info/dependency_links.txt
writing manifest file 'bleah.egg-info/SOURCES.txt'
reading manifest file 'bleah.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching '.DS_Store'
warning: no previously-included files found matching '.gitignore'
warning: no files found matching 'distribute_setup.py'
writing manifest file 'bleah.egg-info/SOURCES.txt'
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    install_requires     = [ 'bluepy', 'terminaltables' ]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 43, in run
    self.build_package_data()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 98, in build_package_data
    for package, src_dir, build_dir, filenames in self.data_files:
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 55, in __getattr__
    self.data_files = files = self._get_data_files()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 81, in _get_data_files
    file[plen:] for file in self.find_data_files(package, src_dir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 89, in find_data_files
    + self.package_data.get(package, []))
TypeError: can only concatenate list (not "str") to list
```

**Comment by turbofocus** [comment]
I solved this issue replacing in the setup.py file the following string:

`package_data         = { 'bleah': os.path.abspath('./bleah/oui.dat') },`

with this one:

`package_data         = { 'bleah': [os.path.abspath('./bleah/oui.dat')] },`

**Comment by ARH-Digital** [comment]
Thanks @turbofocus 
I had to also remove bleah from the array, as I was already in the bleah directory as per the instructions.
````
package_data = { 'bleah': [os.path.abspath('./oui.dat')] },
````

Now when running the bleah command I am met with a new error.

```
root@DESKTOP-L593AS0:~/bleah# bleah -e

          .                                                      .
        .n                   .                 .                  n.
  .   .dP                  dP                   9b                 9b.    .
 4    qXb         .       dX    BLEAH v1.0.0     Xb       .        dXp     t
dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb
9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP
 9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP
  `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'
    `9XXXXXXXXXXXP' `9XX'    *     `98v8P'     *    `XXP' `9XXXXXXXXXXXP'
        ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~
                        )b.  .dbo.dP'`v'`9b.odb.  .dX(
                      ,dXXXXXXXXXXXb     dXXXXXXXXXXXb.
                     dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb
                    dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb
                    9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP
                     `'      9XXXXXX(   )XXXXXXP      `'
                              XXXX X.`v'.X XXXX
                              XP^X'`b   d'`X^XX
                              X. 9  `   '  P )X
                              `b  `       '  d'
                               `             '
                Made with ❤ by Simone 'evilsocket' Margaritelli



@ Scanning for 5s [-128 dBm of sensitivity] ...

Traceback (most recent call last):
  File "/usr/local/bin/bleah", line 5, in <module>
    pkg_resources.run_script('bleah==1.0.0', 'bleah')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 122, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 82, in main
    devices = start_scan(args)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py", line 162, in start_scan
    return scanner.scan(args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 679, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 617, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 272, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 330, in _waitResp
    raise BTLEException(BTLEException.MGMT_ERROR, "Management not available (permissions problem?)")
bluepy.btle.BTLEException: Management not available (permissions problem?)
```

**Comment by ARH-Digital** [comment]
Thanks @turbofocus 
I had to also remove bleah from the array, as I was already in the bleah directory as per the instructions.
````
package_data = { 'bleah': [os.path.abspath('./oui.dat')] },
````

Now when running the bleah command I am met with a new error.

```
root@DESKTOP-L593AS0:~/bleah# bleah -e

          .                                                      .
        .n                   .                 .                  n.
  .   .dP                  dP                   9b                 9b.    .
 4    qXb         .       dX    BLEAH v1.0.0     Xb       .        dXp     t
dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb
9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP
 9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP
  `9XXXXXXXXXXXXXXXXXXXXX'~   ~`OOO8b   d8OOO'~   ~`XXXXXXXXXXXXXXXXXXXXXP'
    `9XXXXXXXXXXXP' `9XX'    *     `98v8P'     *    `XXP' `9XXXXXXXXXXXP'
        ~~~~~~~       9X.          .db|db.          .XP       ~~~~~~~
                        )b.  .dbo.dP'`v'`9b.odb.  .dX(
                      ,dXXXXXXXXXXXb     dXXXXXXXXXXXb.
                     dXXXXXXXXXXXP'   .   `9XXXXXXXXXXXb
                    dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb
                    9XXb'   `XXXXXb.dX|Xb.dXXXXX'   `dXXP
                     `'      9XXXXXX(   )XXXXXXP      `'
                              XXXX X.`v'.X XXXX
                              XP^X'`b   d'`X^XX
                              X. 9  `   '  P )X
                              `b  `       '  d'
                               `             '
                Made with ❤ by Simone 'evilsocket' Margaritelli



@ Scanning for 5s [-128 dBm of sensitivity] ...

Traceback (most recent call last):
  File "/usr/local/bin/bleah", line 5, in <module>
    pkg_resources.run_script('bleah==1.0.0', 'bleah')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 122, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 82, in main
    devices = start_scan(args)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py", line 162, in start_scan
    return scanner.scan(args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 679, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 617, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 272, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 330, in _waitResp
    raise BTLEException(BTLEException.MGMT_ERROR, "Management not available (permissions problem?)")
bluepy.btle.BTLEException: Management not available (permissions problem?)
```

**Comment by ARH-Digital** [comment]
Even the Ubuntu bash within?

**Comment by evilsocket** [comment]
Yes, the Ubuntu sybsystem on Windows is pretty much fake, it does not support low level hardware access as required by bleah.
