### ISSUE TITLE
Error when running bleah - unicode conversion related?

### ISSUE THREAD

**Issue by dsopas** [evilsocket/bleah#2]
When I run:
sudo bleah -i0 -t0

It returns the following error:
```
@ Continuous scanning [-128 dBm of sensitivity] ...

Traceback (most recent call last):
  File "/usr/local/bin/bleah", line 4, in <module>
    __import__('pkg_resources').run_script('bleah==1.0.0', 'bleah')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah",
line 116, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah",
line 76, in main
    devices = start_scan(args)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py",
line 160, in start_scan
    return scanner.scan(args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line
680, in scan
    self.process(timeout)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py",
line 78, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py",
line 140, in handleDiscovery
    tdata.append([ desc, yellow( val.decode('utf-8') ) ])
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in
position 1: ordinal not in range(128)
```

In the past I had issues with this error and what I did was first str.encode('utf-8') then the print it self. I don't know if this is the same issue...

BTW my current settings is:
$LANG - en_US.utf8
python 2.7
Running on a Debian machine.

Thanks!

**Comment by dsopas** [comment]
Perfect! Good job!
