### ISSUE TITLE
rpi3

### ISSUE THREAD

**Issue by megahz** [evilsocket/bleah#27]
hi got this error now:

```
osmc@osmc:~/bleah$ sudo bleah -t0


Traceback (most recent call last):
  File "/usr/local/bin/bleah", line 4, in <module>
    __import__('pkg_resources').run_script('bleah==1.0.0', 'bleah')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 145, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 84, in main
    print_sexy_banner()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/swag.py", line 71, in print_sexy_banner
    print "                " + blue("Made with ") + red(u"\u2764") + blue(" by Simone 'evilsocket' Margaritelli")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2764' in position 40: ordinal not in range(128)
```

**Comment by wouldgo** [comment]
Hi, 

it's related to the installed locale. I think that you should reconfigure `locales` package. I encounter this issue in the past (on a different python application) because I had `LC_ALL` variable set with `C`.
At the end choosing `en_US.UTF-8 UTF-8` worked.

**Comment by megahz** [comment]
thanks @wouldgo this resolved the issue.
