### ISSUE TITLE
"TypeError: can only concatenate list to list"

### ISSUE THREAD

**Issue by pcabreracamara** [evilsocket/bleah#4]
Hi,

Last night I was able to build and install on Ubuntu 16, but now I'm trying on Ubutu 14 but get this error when trying "python setup.py build";

```
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    install_requires     = [ 'bluepy', 'terminaltables' ]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 52, in run
    self.build_package_data()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 107, in build_package_data
    for package, src_dir, build_dir, filenames in self.data_files:
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 65, in __getattr__
    self.data_files = self._get_data_files()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 79, in _get_data_files
    return list(map(self._get_pkg_data_files, self.packages or ()))
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
    for file in self.find_data_files(package, src_dir)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 98, in find_data_files
    + self.package_data.get(package, []))
TypeError: can only concatenate list (not "str") to list
```

Could you please give me some help to overcome the installation ?

I really appreciate any help you can provide.

**Comment by MarioVillani** [comment]
Make sure to have `setuptools` and  `buildtools` at the latest version. I've fixed this issue by upgrading them.

**Comment by pcabreracamara** [comment]
Yep !!  Thank you very much.
